export const CATEGORIES = [
  { id: 1, key: "produce", title: "Produce", image: require("../assets/categories/cat_produce.jpg") },
  { id: 2, key: "meat", title: "Meat", image: require("../assets/categories/cat_meat.jpg") },
  { id: 3, key: "baked", title: "Bakery", image: require("../assets/categories/cat_bakery.jpg") },
  { id: 4, key: "eggs_dairy", title: "Eggs & Dairy", image: require("../assets/categories/cat_eggs_dairy.jpg") },
  { id: 5, key: "herbs", title: "Herbs", image: require("../assets/categories/cat_herbs.jpg") },
  { id: 6, key: "candles", title: "Candles", image: require("../assets/categories/cat_candles.jpg") },
  { id: 7, key: "jewelry", title: "Jewelry", image: require("../assets/categories/cat_jewelry.jpg") },
  { id: 8, key: "clothing", title: "Clothing", image: require("../assets/categories/cat_clothing.jpg") },
  { id: 9, key: "coffee_tea", title: "Coffee & Tea", image: require("../assets/categories/cat_coffee_tea.jpg") },
  { id: 10, key: "crafts", title: "Crafts", image: require("../assets/categories/cat_crafts.jpg") },
  { id: 11, key: "honey_jams", title: "Honey & Jams", icon: "nutrition-outline" },
  { id: 12, key: "flowers", title: "Flowers", image: require("../assets/categories/cat_flowers.jpg") },
  { id: 13, key: "soaps", title: "Soaps", image: require("../assets/categories/cat_soaps.jpg") },
  { id: 14, key: "home_living", title: "Home Living", image: require("../assets/categories/cat_home_living.jpg") },
  { id: 15, key: "pantry", title: "Pantry", image: require("../assets/categories/cat_pantry.jpg") },
  { id: 16, key: "wellness", title: "Wellness", image: require("../assets/categories/cat_wellness.jpg") },
  { id: 17, key: "pet_products", title: "Pet Products", image: require("../assets/categories/cat_pet_products.jpg") },
  { id: 18, key: "nuts", title: "Nuts", image: require("../assets/categories/cat_nuts.jpg") },
  { id: 19, key: "sauces", title: "Sauces", image: require("../assets/categories/cat_sauces.jpg") },
  { id: 20, key: "spices", title: "Spices", image: require("../assets/categories/cat_spices.jpg") },
  { id: 21, key: "essential_oils", title: "Essential Oils", image: require("../assets/categories/cat_essential_oils.jpg") },
  { id: 22, key: "farm_garden", title: "Farm & Garden", image: require("../assets/categories/cat_barn.jpg") },
  { id: 23, key: "plants", title: "Plants", image: require("../assets/categories/cat_plants.jpg") },
  { id: 24, key: "local_makers", title: "Local Makers", image: require("../assets/categories/cat_local_makers.jpg") },
  { id: 25, key: "gifts", title: "Gift Sets", image: require("../assets/categories/cat_gifts.jpg") },
  { id: 26, key: "seasonal", title: "Seasonal", image: require("../assets/categories/cat_seasonal.jpg") },
  { id: 27, key: "candy", title: "Candy", image: require("../assets/categories/cat_candy.jpg") },
];