export const CATEGORIES = [
  { id: 1, title: "Produce", image: require("../assets/categories/cat_produce.jpg") },
  { id: 2, title: "Meat", image: require("../assets/categories/cat_meat.jpg") },
  { id: 3, title: "Bakery", image: require("../assets/categories/cat_bakery.jpg") },
  { id: 4, title: "Eggs & Dairy", image: require("../assets/categories/cat_eggs_dairy.jpg") },
  { id: 5, title: "Herbs", image: require("../assets/categories/cat_herbs.jpg") },
  { id: 6, title: "Candles", image: require("../assets/categories/cat_candles.jpg") },
  { id: 7, title: "Jewelry", image: require("../assets/categories/cat_jewelry.jpg") },
  { id: 8, title: "Clothing", image: require("../assets/categories/cat_clothing.jpg") },
  { id: 9, title: "Coffee & Tea", image: require("../assets/categories/cat_coffee_tea.jpg") },
  { id: 10, title: "Crafts", image: require("../assets/categories/cat_crafts.jpg") },
  { id: 11, title: "Honey & Jams", image: require("../assets/categories/cat_honey_jams.jpg") },
  { id: 12, title: "Flowers", image: require("../assets/categories/cat_flowers.jpg") },
  { id: 13, title: "Soaps", image: require("../assets/categories/cat_soaps.jpg") },
  { id: 14, title: "Home Living", image: require("../assets/categories/cat_home_living.jpg") },
  { id: 15, title: "Pantry", image: require("../assets/categories/cat_pantry.jpg") },
  { id: 16, title: "Wellness", image: require("../assets/categories/cat_wellness.jpg") },
  { id: 17, title: "Pet Products", image: require("../assets/categories/cat_pet_products.jpg") },
  { id: 18, title: "Nuts", image: require("../assets/categories/cat_nuts.jpg") },
  { id: 19, title: "Sauces", image: require("../assets/categories/cat_sauces.jpg") },
  { id: 20, title: "Spices", image: require("../assets/categories/cat_spices.jpg") },
  { id: 21, title: "Essential Oils", image: require("../assets/categories/cat_essential_oils.jpg") },
  { id: 22, title: "Farm & Garden", image: require("../assets/categories/cat_barn.jpg") },
  { id: 23, title: "Plants", image: require("../assets/categories/cat_plants.jpg") },
  { id: 24, title: "Local Makers", image: require("../assets/categories/cat_local_makers.jpg") },
  { id: 25, title: "Gift Sets", image: require("../assets/categories/cat_gifts.jpg") },
  { id: 26, title: "Seasonal", image: require("../assets/categories/cat_seasonal.jpg") },
  { id: 27, title: "Candy", image: require("../assets/categories/cat_candy.jpg") },
];