import React, { useEffect, useState } from 'react';
import { View, Text, Image, ScrollView, FlatList, StyleSheet, SafeAreaView, StatusBar, ActivityIndicator, TouchableOpacity, Alert, RefreshControl, Linking } from 'react-native';
import AppButton from '../../components/AppButton';
import EmptyState from '../../components/EmptyState';
import { COLORS, FONTS, LAYOUT, RADIUS, SHADOWS } from '../../constants/theme';
import { IMAGE_ASSETS } from '../../constants/assets';

export default function VendorProductsScreen({ API, token }) {
  const [products,setProducts]=useState([]), [loading,setLoading]=useState(true);
  useEffect(()=>{load()},[]);
  async function load(){setLoading(true);try{const r=await fetch(`${API}/api/products/my`,{headers:{Authorization:'Bearer '+token}});const d=await r.json();setProducts(Array.isArray(d)?d:[])}catch{setProducts([])}setLoading(false)}
  async function toggle(p){try{const r=await fetch(`${API}/api/products/${p.id}`,{method:'PATCH',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({is_active:!p.is_active})}); if(!r.ok)throw new Error(); load()}catch{Alert.alert('Unable to update product','Please try again.')}}
  if(loading)return <View style={styles.root}><SafeAreaView style={styles.center}><ActivityIndicator color={COLORS.forest}/><Text style={styles.muted}>Loading products...</Text></SafeAreaView></View>;
  return <View style={styles.root}><StatusBar barStyle="dark-content" backgroundColor={COLORS.cream}/><SafeAreaView style={styles.root}><FlatList data={products} keyExtractor={i=>String(i.id)} contentContainerStyle={styles.list}
    ListHeaderComponent={<View style={styles.header}><Text style={styles.eyebrow}>Inventory</Text><Text style={styles.title}>Products</Text><Text style={styles.subtitle}>Manage what customers can discover and purchase.</Text><AppButton title="Add Product Coming Next" onPress={()=>Alert.alert('Coming next','We will wire this next.')} style={{marginTop:16}}/></View>}
    ListEmptyComponent={<EmptyState image={IMAGE_ASSETS.products.default} title="No products yet" message="Add products so customers can shop your goods." buttonTitle="Add Product Coming Next" onPress={()=>{}}/>}
    renderItem={({item})=><View style={styles.card}><Image source={item.image_url?{uri:item.image_url}:IMAGE_ASSETS.products.default} style={styles.image}/><View style={styles.body}><View style={styles.top}><View style={{flex:1}}><Text style={styles.name}>{item.name}</Text><Text style={styles.cat}>{item.category}</Text></View><Text style={styles.price}>${Number(item.price||0).toFixed(2)}</Text></View>{!!item.description&&<Text style={styles.desc} numberOfLines={2}>{item.description}</Text>}<View style={styles.meta}><Text style={styles.pill}>{item.quantity_available} available</Text><Text style={styles.pill}>{item.unit}</Text><Text style={[styles.status,!item.is_active&&styles.inactive]}>{item.is_active?'Active':'Hidden'}</Text></View><View style={styles.actions}><AppButton title={item.is_active?'Hide':'Activate'} variant="outline" onPress={()=>toggle(item)} style={styles.small}/><AppButton title="Edit Coming Next" variant="secondary" onPress={()=>{}} style={styles.small}/></View></View></View>}
  /></SafeAreaView></View>
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:COLORS.cream},center:{flex:1,alignItems:'center',justifyContent:'center'},muted:{fontFamily:FONTS.body,color:COLORS.brownSoft,marginTop:10},list:{paddingHorizontal:LAYOUT.screenPadding,paddingBottom:118},header:{paddingTop:14,marginBottom:18},eyebrow:{fontFamily:FONTS.bodyBold,fontSize:12,letterSpacing:1.2,textTransform:'uppercase',color:COLORS.sage},title:{fontFamily:FONTS.display,fontSize:34,color:COLORS.forestDark,marginTop:4},subtitle:{fontFamily:FONTS.body,fontSize:14,lineHeight:21,color:COLORS.brownSoft,marginTop:6},card:{backgroundColor:COLORS.warmWhite,borderRadius:RADIUS.xl,borderWidth:1,borderColor:COLORS.border,overflow:'hidden',marginBottom:16,...SHADOWS.soft},image:{width:'100%',height:170,backgroundColor:COLORS.beige},body:{padding:16},top:{flexDirection:'row',justifyContent:'space-between',gap:12},name:{fontFamily:FONTS.display,fontSize:24,color:COLORS.forestDark},cat:{fontFamily:FONTS.bodyBold,fontSize:12,color:COLORS.sage,marginTop:3,textTransform:'capitalize'},price:{fontFamily:FONTS.display,fontSize:23,color:COLORS.forest},desc:{fontFamily:FONTS.body,fontSize:13,lineHeight:19,color:COLORS.brown,marginTop:8},meta:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12},pill:{fontFamily:FONTS.bodyBold,fontSize:11,color:COLORS.brownSoft,backgroundColor:COLORS.beige,borderRadius:RADIUS.pill,paddingHorizontal:10,paddingVertical:6,overflow:'hidden'},status:{fontFamily:FONTS.bodyBold,fontSize:11,color:COLORS.success,backgroundColor:COLORS.sageSoft,borderRadius:RADIUS.pill,paddingHorizontal:10,paddingVertical:6,overflow:'hidden'},inactive:{color:COLORS.danger,backgroundColor:'#F7DDD6'},actions:{flexDirection:'row',gap:10,marginTop:14},small:{flex:1,minHeight:44}})
