import React, { useEffect, useState } from 'react';
import { View, Text, Image, ScrollView, FlatList, StyleSheet, SafeAreaView, StatusBar, ActivityIndicator, TouchableOpacity, Alert, RefreshControl, Linking } from 'react-native';
import AppButton from '../../components/AppButton';
import EmptyState from '../../components/EmptyState';
import { COLORS, FONTS, LAYOUT, RADIUS, SHADOWS } from '../../constants/theme';
import { IMAGE_ASSETS } from '../../constants/assets';

const NEXT={pending:[['Confirm','confirmed','primary'],['Cancel','cancelled','outline']],confirmed:[['Ready for Pickup','ready_for_pickup','primary'],['Out for Delivery','out_for_delivery','secondary']],ready_for_pickup:[['Mark Fulfilled','fulfilled','primary']],out_for_delivery:[['Mark Fulfilled','fulfilled','primary']]};
export default function VendorOrdersScreen({ API, token }) {
  const [orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);
  useEffect(()=>{load()},[]);
  async function load(ref=false){ref?setRefreshing(true):setLoading(true);try{const r=await fetch(`${API}/api/orders/producer/incoming`,{headers:{Authorization:'Bearer '+token}});const d=await r.json();setOrders(Array.isArray(d)?d:[])}catch{setOrders([])}setLoading(false);setRefreshing(false)}
  async function update(id,status){try{const r=await fetch(`${API}/api/orders/${id}/status`,{method:'PATCH',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({status})}); const d=await r.json(); if(!r.ok) throw new Error(d.detail||'Update failed'); load()}catch(e){Alert.alert('Order update failed',e.message||'Please try again.')}}
  if(loading)return <View style={styles.root}><SafeAreaView style={styles.center}><ActivityIndicator color={COLORS.forest}/><Text style={styles.muted}>Loading orders...</Text></SafeAreaView></View>;
  return <View style={styles.root}><StatusBar barStyle="dark-content" backgroundColor={COLORS.cream}/><SafeAreaView style={styles.root}><FlatList data={orders} keyExtractor={i=>String(i.id)} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)} tintColor={COLORS.forest}/>} contentContainerStyle={styles.list}
    ListHeaderComponent={<View style={styles.header}><Text style={styles.eyebrow}>Vendor orders</Text><Text style={styles.title}>Incoming orders</Text><Text style={styles.subtitle}>Confirm, prepare, and complete customer orders.</Text></View>}
    ListEmptyComponent={<EmptyState image={IMAGE_ASSETS.hero.checkout} title="No orders yet" message="Orders will appear here once customers purchase." buttonTitle="Refresh" onPress={()=>load()}/>}
    renderItem={({item})=><View style={styles.card}><View style={styles.top}><View><Text style={styles.orderNo}>Order #{item.id}</Text><Text style={styles.customer}>{item.shopper_name}</Text></View><Text style={styles.total}>${Number(item.total||0).toFixed(2)}</Text></View><View style={styles.meta}><Text style={styles.badge}>{item.status}</Text><Text style={styles.badge}>{item.fulfillment_type}</Text>{item.status==='pending'&&<Text style={styles.warning}>{Number(item.hours_remaining||0).toFixed(1)} hrs left</Text>}</View><View style={styles.actions}>{(NEXT[item.status]||[]).map(([label,status,variant])=><AppButton key={status} title={label} variant={variant} onPress={()=>update(item.id,status)} style={styles.action}/>)}</View></View>}
  /></SafeAreaView></View>
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:COLORS.cream},center:{flex:1,alignItems:'center',justifyContent:'center'},muted:{fontFamily:FONTS.body,color:COLORS.brownSoft,marginTop:10},list:{paddingHorizontal:LAYOUT.screenPadding,paddingBottom:118},header:{paddingTop:14,marginBottom:18},eyebrow:{fontFamily:FONTS.bodyBold,fontSize:12,letterSpacing:1.2,textTransform:'uppercase',color:COLORS.sage},title:{fontFamily:FONTS.display,fontSize:34,color:COLORS.forestDark,marginTop:4},subtitle:{fontFamily:FONTS.body,fontSize:14,lineHeight:21,color:COLORS.brownSoft,marginTop:6},card:{backgroundColor:COLORS.warmWhite,borderRadius:RADIUS.xl,borderWidth:1,borderColor:COLORS.border,padding:16,marginBottom:16,...SHADOWS.soft},top:{flexDirection:'row',justifyContent:'space-between',gap:14},orderNo:{fontFamily:FONTS.bodyBold,fontSize:13,color:COLORS.sage},customer:{fontFamily:FONTS.display,fontSize:24,color:COLORS.forestDark,marginTop:3},total:{fontFamily:FONTS.display,fontSize:24,color:COLORS.forest},meta:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:14},badge:{fontFamily:FONTS.bodyBold,fontSize:11,color:COLORS.forest,backgroundColor:COLORS.sageSoft,paddingHorizontal:10,paddingVertical:6,borderRadius:RADIUS.pill,overflow:'hidden',textTransform:'capitalize'},warning:{fontFamily:FONTS.bodyBold,fontSize:11,color:COLORS.rust,backgroundColor:'#FDE8DC',paddingHorizontal:10,paddingVertical:6,borderRadius:RADIUS.pill,overflow:'hidden'},actions:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:16},action:{flex:1,minWidth:130,minHeight:44}})
