import React, { useEffect, useState } from 'react';
import { View, Text, Image, ScrollView, FlatList, StyleSheet, SafeAreaView, StatusBar, ActivityIndicator, TouchableOpacity, Alert, RefreshControl, Linking } from 'react-native';
import AppButton from '../../components/AppButton';
import EmptyState from '../../components/EmptyState';
import { COLORS, FONTS, LAYOUT, RADIUS, SHADOWS } from '../../constants/theme';
import { IMAGE_ASSETS } from '../../constants/assets';

export default function VendorProfileScreen({ API, token, user, setToken, setUser }) {
  const [shop,setShop]=useState(null),[loading,setLoading]=useState(true);
  useEffect(()=>{load()},[]);
  async function load(){setLoading(true);try{const r=await fetch(`${API}/api/producers/me`,{headers:{Authorization:'Bearer '+token}});const d=await r.json();setShop(r.ok?d:null)}catch{setShop(null)}setLoading(false)}
  function logout(){setToken(null);setUser(null)}
  if(loading)return <View style={styles.root}><SafeAreaView style={styles.center}><ActivityIndicator color={COLORS.forest}/><Text style={styles.muted}>Loading store...</Text></SafeAreaView></View>;
  if(!shop)return <View style={styles.root}><SafeAreaView style={styles.empty}><EmptyState image={IMAGE_ASSETS.vendor.storefront} title="Store setup needed" message="Your vendor account exists, but your storefront has not been created yet." buttonTitle="Setup Flow Coming Next" onPress={()=>{}}/><AppButton title="Sign Out" variant="outline" onPress={logout} style={{marginTop:14}}/></SafeAreaView></View>;
  const img=shop.profile_image_url?{uri:shop.profile_image_url}:IMAGE_ASSETS.vendor.storefront;
  return <View style={styles.root}><StatusBar barStyle="dark-content" backgroundColor={COLORS.cream}/><SafeAreaView style={styles.root}><ScrollView contentContainerStyle={styles.scroll}><View style={styles.hero}><Image source={img} style={styles.heroImg}/><View style={styles.overlay}/><View style={styles.heroCopy}><Text style={styles.eyebrow}>Vendor store</Text><Text style={styles.titleLight}>{shop.shop_name}</Text><Text style={styles.heroSub}>{shop.city||'Local'}{shop.state?`, ${shop.state}`:''}</Text></View></View><View style={styles.card}><Text style={styles.cardTitle}>Public storefront</Text><Text style={styles.body}>{shop.description||'Add a store description so customers understand what you sell.'}</Text><View style={styles.grid}><Info label="Pickup" value={shop.fulfillment_pickup?'Enabled':'Off'}/><Info label="Delivery" value={shop.fulfillment_delivery?'Enabled':'Off'}/><Info label="Shipping" value={shop.fulfillment_shipping?'Enabled':'Off'}/></View><AppButton title="Edit Store Coming Next" onPress={()=>Alert.alert('Coming next','We will wire this next.')} style={{marginTop:16}}/></View><View style={styles.card}><Text style={styles.cardTitle}>Owner account</Text><Text style={styles.body}>{user?.full_name||'Vendor'} · {user?.email||'Vendor account'}</Text><AppButton title="Sign Out" variant="outline" onPress={logout} style={{marginTop:16}}/></View></ScrollView></SafeAreaView></View>
}
function Info({label,value}){return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:COLORS.cream},center:{flex:1,alignItems:'center',justifyContent:'center'},muted:{fontFamily:FONTS.body,color:COLORS.brownSoft,marginTop:10},empty:{flex:1,padding:LAYOUT.screenPadding,justifyContent:'center'},scroll:{paddingHorizontal:LAYOUT.screenPadding,paddingBottom:118},hero:{height:280,borderRadius:RADIUS.xl,overflow:'hidden',marginTop:14,...SHADOWS.card},heroImg:{width:'100%',height:'100%'},overlay:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(23,50,31,.36)'},heroCopy:{position:'absolute',left:20,right:20,bottom:22},eyebrow:{fontFamily:FONTS.bodyBold,fontSize:12,letterSpacing:1.2,textTransform:'uppercase',color:COLORS.cream},titleLight:{fontFamily:FONTS.display,fontSize:34,color:COLORS.warmWhite,marginTop:6},heroSub:{fontFamily:FONTS.bodyBold,fontSize:13,color:COLORS.cream,marginTop:6},card:{marginTop:18,backgroundColor:COLORS.warmWhite,borderRadius:RADIUS.xl,borderWidth:1,borderColor:COLORS.border,padding:18,...SHADOWS.soft},cardTitle:{fontFamily:FONTS.display,fontSize:25,color:COLORS.forestDark},body:{fontFamily:FONTS.body,fontSize:14,lineHeight:22,color:COLORS.brown,marginTop:8},grid:{flexDirection:'row',gap:10,marginTop:16},info:{flex:1,backgroundColor:COLORS.cream,borderRadius:RADIUS.lg,padding:12,alignItems:'center'},infoLabel:{fontFamily:FONTS.bodyBold,fontSize:11,color:COLORS.brownSoft},infoValue:{fontFamily:FONTS.bodyBold,fontSize:13,color:COLORS.forest,marginTop:4}})
